- shell:
    -
      command: "echo yes | /bin/bash -c \"$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)\""
      description: Installing Homebrew
      stdout: true
    - [ brew bundle --file Brewfile.mac, Install dependencies]

