- shell:
    - [ groupadd -f docker, Adding Docker group... ]
    - [ usermod -aG docker $USER, Adding user to Docker group... ]
    - [ docker pull ghcr.io/ecarlson94/userspace:main, Downloaiding userspace container... ]
